package ch.bfh.bti7081.s2013.pink;

import java.text.SimpleDateFormat;

import ch.bfh.bti7081.s2013.pink.model.Patient;
import ch.bfh.bti7081.s2013.pink.model.Session;

import com.vaadin.server.ClassResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Layout;
import com.vaadin.ui.VerticalLayout;

/**
 * Class that shows the upcomming sessions with the patients
 * 
 * @author Marco Berger <lostchall@gmail.com>
 */
@SuppressWarnings("serial")
public class PatientOverview extends CustomComponent {
	private SimpleDateFormat dateFormat = new SimpleDateFormat();
	private HorizontalLayout mainLayout;

	private Label name;
	private Label firstName;
	private Label sessionBegin;

	private Patient patient;
	private Session session;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PatientOverview(int posX, int posY, Patient patient, Session session) {
		this.patient = patient;
		this.session = session;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private Layout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setWidth("100%");

		// VerticalLayout content = new VerticalLayout();

		HorizontalLayout names = new HorizontalLayout();
		names.setWidth("100%");
		Layout patientGroup = new VerticalLayout();
		Layout sessionGroup = new VerticalLayout();

		// Name
		name = new Label();
		name.setCaption("Name");
		name.setImmediate(false);
		name.setValue(patient.getFirstName() + " " + patient.getName());
		names.addComponent(name);
		// First Name
		// firstName = new Label();
		// firstName.setCaption("First Name");
		// firstName.setImmediate(false);
		// firstName.setValue(patient.getFirstName());
		// names.addComponent(firstName);
		// names.setExpandRatio(name, 1.0f);
		// names.setExpandRatio(firstName, 1.0f);

		mainLayout.addComponent(names);

		// Adds the button to start the patient session
		Button buttonShowDetails = new Button("Patient Details",
				new Button.ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						// Open Search
						PatientDetailView detailedPatientView = new PatientDetailView(
								patient);
						MyVaadinUI.getNavigationManager().navigateTo(
								detailedPatientView);
						// getUI().getNavigator().addView("patientDetail",
						// detailedPatientView);
						// getUI().getNavigator().navigateTo("patientDetail");
					}
				});
		patientGroup.addComponent(names);
		patientGroup.addComponent(buttonShowDetails);

		// SessionBegin
		sessionBegin = new Label();
		sessionBegin.setCaption("Session begin:");
		sessionBegin.setImmediate(false);
		// TODO: Date formatting
		String startTime = dateFormat.format(session.getTimeStart());
		sessionBegin.setValue(startTime);
		sessionGroup.addComponent(sessionBegin);

		// Adds the button to start the patient session
		Button startSession = new Button("Start Session",
				new Button.ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						// Open Search
						// PatientDetailView detailedPatientView = new
						// PatientDetailView(patient);
						// getUI().getNavigator().addView("sessionDetail", de)
						// mainLayout.addComponent(detailledPatientView);
					}
				});
		sessionGroup.addComponent(startSession);

		mainLayout.addComponent(new Image(null, new ClassResource(
				"/images/mascot.png")));
		mainLayout.addComponent(patientGroup);
		mainLayout.addComponent(sessionGroup);
		mainLayout.setExpandRatio(patientGroup, 1.0f);
		mainLayout.setExpandRatio(sessionGroup, 1.0f);

		return mainLayout;
	}
}