package ch.bfh.bti7081.s2013.pink;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Resource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

/**
 * View class that allows to search for a patient.
 * 
 * @author Marco Berger <lostchall@gmail.com>
 * 
 */
@SuppressWarnings("serial")
public class PatientSearchView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	private Label title;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PatientSearchView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("90px");

		// top-level component properties
		setWidth("100.0%");
		setHeight("90px");

		// Set BG
		Resource res = new ThemeResource("img/searchBG.png");

		// Display the image without caption
		Image searchbg = new Image(null, res);
		mainLayout.addComponent(searchbg);

		// Create the search field
		TextField tf = new TextField("Search for patient");

		// Put some initial content in it
		// tf.setValue("");/*
		mainLayout.addComponent(tf, "top:30px;left:200px;");

		// Next Sessions
		title = new Label();
		title.setValue("Next sessions");
		mainLayout.addComponent(title, "top:70px;left:200px;");
		SearchButton searchButton = new SearchButton();
		mainLayout.addComponent(searchButton, "top:30px;left:330px;");
		return mainLayout;
	}

	public class SearchButton extends CustomComponent implements
			Button.ClickListener {
		Button searchbutton;

		public SearchButton() {
			// Create a Button with the given caption.
			searchbutton = new Button("Search");

			// Listen for ClickEvents.
			searchbutton.addClickListener(this);

			setCompositionRoot(searchbutton);
		}

		/** Handle search events for the button. */
		public void buttonClick(Button.ClickEvent event) {
			// TODO
			// Open Search
			// PatientDetailView detailledPatientView = new PatientDetailView(
			// patient);
			// mainLayout.addComponent(detailledPatientView);
		}
	}

	public void patientSearch(String searchTag) {
		//
	}
}