/**
 * Class that shows the upcomming sessions with the patients
 *
 * @author	Marco Berger	<lostchall@gmail.com>
 */
package ch.bfh.bti7081.s2013.pink;

import ch.bfh.bti7081.s2013.pink.model.Patient;
import ch.bfh.bti7081.s2013.pink.model.Session;
import ch.bfh.bti7081.s2013.pink.view.PatientDetailView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.BrowserWindowOpener;
import com.vaadin.server.Resource;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;

@SuppressWarnings("serial")
public class SessionWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	private Label title;
	private Patient patient;
	private Session session;
	private String noteValue;

	// private List<Warning> warnings;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SessionWindow(Session session, Patient patient) {
		this.session = session;
		this.patient = patient;

		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100%");

		// Set BG
		Resource res = new ThemeResource("img/patient_bg.png");

		// Display the patient image
		Image bgImage = new Image(null, res);
		mainLayout.addComponent(bgImage, "top:50;left:180px;");

		// Patient information
		title = new Label();
		title.setValue("Session of " + patient.getFirstName() + " "
				+ patient.getName());
		mainLayout.addComponent(title, "top:70px;left:200px;");

		// Create title field
		TextArea tf = new TextArea("Session notes");
		tf.setWidth("550px");
		tf.setHeight("320px");
		mainLayout.addComponent(tf, "top:200px;left:200px;");

		// Session start time
		title = new Label();
		title.setValue("Start time:");
		mainLayout.addComponent(title, "top:100px;left:200px;");

		// start time value
		title = new Label();
		title.setValue(session.getTimeStart().toString());
		mainLayout.addComponent(title, "top:100px;left:270px;");
		// Session end time
		title = new Label();
		title.setValue("End time:");
		mainLayout.addComponent(title, "top:130px;left:200px;");

		// end time value
		title = new Label();
		title.setValue(session.getTimeEnd().toString());
		mainLayout.addComponent(title, "top:130px;left:270px;");

		// add add Note button
		Button addNote = new Button("Add note", new Button.ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				// Open Search
				PatientDetailView detailedPatientView = new PatientDetailView(
						patient);
				MyVaadinUI.getNavigationManager().navigateTo(
						detailedPatientView);
			}
		});
		mainLayout.addComponent(addNote, "top:530px;left:200px");

		// add add medicdation button
		Button closeSessionButton = new Button("End session",
				new Button.ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						// Open Search
						PatientDetailView detailedPatientView = new PatientDetailView(
								patient);
						MyVaadinUI.getNavigationManager().navigateTo(
								detailedPatientView);
					}
				});
		mainLayout.addComponent(closeSessionButton, "top:70px;left:450px");
		// closeSessionButton.addListener(new ClickListener());

		// add end session button
		Button addMedicationButton = new Button("Add medication",
				new Button.ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						// Open Search
						PatientDetailView detailedPatientView = new PatientDetailView(
								patient);
						MyVaadinUI.getNavigationManager().navigateTo(
								detailedPatientView);
					}
				});
		mainLayout.addComponent(addMedicationButton, "top:100px;left:450px");

		// Create an opener extension
		BrowserWindowOpener opener = new BrowserWindowOpener(
				ShowWarningView.class);
		opener.setFeatures("height=200,width=300,resizable");

		// Attach it to a button
		Button warnings = new Button("Show warnings");
		warnings.setIcon(new ThemeResource("img/warning.png"));
		opener.extend(warnings);
		mainLayout.addComponent(warnings, "top:130px;left:450px");
		return mainLayout;
	}

}