/**
 * Class that shows the upcomming sessions with the patients
 *
 * @author	Marco Berger	<lostchall@gmail.com>
 */
package ch.bfh.bti7081.s2013.pink;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Collection;

import ch.bfh.bti7081.s2013.pink.model.HibernateDataSource;
import ch.bfh.bti7081.s2013.pink.model.Note;
import ch.bfh.bti7081.s2013.pink.model.Patient;
import ch.bfh.bti7081.s2013.pink.model.Session;
import ch.bfh.bti7081.s2013.pink.model.SessionState;
import ch.bfh.bti7081.s2013.pink.view.IndicatorImageSource;
import ch.bfh.bti7081.s2013.pink.view.MedicalPrescriptionView;
import ch.bfh.bti7081.s2013.pink.view.NotesPopover;
import ch.bfh.bti7081.s2013.pink.view.WarningPopover;
import ch.bfh.bti7081.s2013.pink.view.WarningPopover.UpdateListener;

import com.vaadin.addon.touchkit.ui.HorizontalButtonGroup;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.addon.touchkit.ui.Toolbar;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.FieldEvents;
import com.vaadin.server.ClassResource;
import com.vaadin.ui.AbstractComponentContainer;
import com.vaadin.ui.AbstractTextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class SessionView extends NavigationView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	private TextArea tf;
	private Patient patient;
	private Session session;
	private String noteValue;
	private HibernateDataSource ds = HibernateDataSource.getInstance();

	private DateFormat df = new SimpleDateFormat();
	private Button startSessionButton;
	private Button finishSessionButton;
	private Button abortSessionButton;
	private Button reopenSessionButton;
	private Button cancelSessionButton;
	private Button archiveSessionButton;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public SessionView(Session session, Patient patient) {
		setCaption(patient.getFirstName() + "'s Session");

		this.session = session;
		this.patient = patient;

		buildMainLayout();

		setContent(mainLayout);

		setToolbar(createToolbar());
	}

	private Toolbar createToolbar() {
		Toolbar toolbar = new Toolbar();

		final Button notesButton = new Button();
		notesButton.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 7701758595488212194L;

			@Override
			public void buttonClick(ClickEvent event) {
				NotesPopover notesView = new NotesPopover(session);
				// MyVaadinUI.getNavigationManager().navigateTo(notesView);
				notesView.showRelativeTo(notesButton);
			}
		});
		int size = session.getNotes().size();
		IndicatorImageSource image = new IndicatorImageSource(
				"/images/note.png", size);
		notesButton.setIcon(image.getResource());
		toolbar.addComponent(notesButton);

		final Button warningsButton = new Button();
		warningsButton.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = -332160668612432938L;

			@Override
			public void buttonClick(ClickEvent event) {
				WarningPopover popover = new WarningPopover(patient);

				// Show it relative to the navigation bar of
				// the current NavigationView.
				popover.showRelativeTo(warningsButton);
				popover.addUpdateListener(new UpdateListener() {
					@Override
					public void update(int size) {
						IndicatorImageSource image = new IndicatorImageSource(
								"/images/warning.png", size);
						warningsButton.setIcon(image.getResource());
						patient = ds.reload(patient);
					}
				});
			}
		});
		size = patient.getWarnings().size();
		image = new IndicatorImageSource("/images/warning.png", size);
		warningsButton.setIcon(image.getResource());
		toolbar.addComponent(warningsButton);

		return toolbar;
	}

	private AbstractComponentContainer buildInfo() {
		VerticalLayout layout = new VerticalLayout();
		layout.setWidth("100%");
		layout.setSpacing(true);

		HorizontalLayout imageAndText = new HorizontalLayout();
		layout.addComponent(imageAndText);
		imageAndText.setWidth("100%");
		imageAndText.setSpacing(true);

		VerticalComponentGroup times = new VerticalComponentGroup();
		layout.addComponent(times);
		times.setWidth("100%");

		// set patient picture
		if (patient.getImageUrl() != null) {
			Image image = new Image(null, new ClassResource(
					patient.getImageUrl()));
			imageAndText.addComponent(image);
		}

		VerticalLayout vl = new VerticalLayout();
		imageAndText.addComponent(vl);
		imageAndText.setExpandRatio(vl, 0.7f);

		// TODO: Show Session State!

		// Patient information
		Label title = new Label();
		title.setValue("Session of " + patient.getFirstName() + " "
				+ patient.getName());
		vl.addComponent(title);

		// Buttons
		buildButtons(vl);

		// Session start time
		Label sessionStart = new Label();
		sessionStart.setCaption("Start");
		sessionStart.setValue(df.format(session.getTimeStart()));
		times.addComponent(sessionStart);

		// Session end time
		Label titleEnd = new Label();
		titleEnd.setCaption("End");
		titleEnd.setValue(df.format(session.getTimeEnd()));
		times.addComponent(titleEnd);
		return layout;
	}

	private void buildButtons(AbstractComponentContainer group) {
		HorizontalButtonGroup stateButtons = new HorizontalButtonGroup();
		stateButtons.setWidth("100%");
		group.addComponent(stateButtons);
		HorizontalButtonGroup mediNoteButtons = new HorizontalButtonGroup();
		mediNoteButtons.setWidth("100%");
		group.addComponent(mediNoteButtons);

		// add start session button
		startSessionButton = new Button("Start Session", new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				session.changeState(SessionState.STARTED);
				session = ds.saveOrUpdate(session);
				updateButtons();
			}
		});
		startSessionButton.setWidth("100%");
		stateButtons.addComponent(startSessionButton);

		// add finish session button
		finishSessionButton = new Button("Finish session", new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				session.changeState(SessionState.FINISHED);
				session = ds.saveOrUpdate(session);
				updateButtons();
			}
		});
		finishSessionButton.setWidth("100%");
		stateButtons.addComponent(finishSessionButton);

		// add abort session button
		abortSessionButton = new Button("Abort session", new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				session.changeState(SessionState.ABORTED);
				session = ds.saveOrUpdate(session);
				updateButtons();
			}
		});
		abortSessionButton.setWidth("100%");
		stateButtons.addComponent(abortSessionButton);

		// add reopen session button
		reopenSessionButton = new Button("Reopen session", new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				session.changeState(SessionState.REOPENED);
				session = ds.saveOrUpdate(session);
				updateButtons();
			}
		});
		reopenSessionButton.setWidth("100%");
		stateButtons.addComponent(reopenSessionButton);

		// add cancel session button
		cancelSessionButton = new Button("Cancel session", new ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				session.changeState(SessionState.CANCELLED);
				session = ds.saveOrUpdate(session);
				updateButtons();
			}
		});
		cancelSessionButton.setWidth("100%");
		stateButtons.addComponent(cancelSessionButton);

		// add archive session button
		archiveSessionButton = new Button("Archive session",
				new ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						session.changeState(SessionState.ARCHIVED);
						session = ds.saveOrUpdate(session);
						updateButtons();
					}
				});
		archiveSessionButton.setWidth("100%");
		stateButtons.addComponent(archiveSessionButton);

		// And now for something completely different:
		// add add medication button
		// TODO: Should this be in the toolbar?
		Button addMedicationButton = new Button("Add medication",
				new Button.ClickListener() {
					@Override
					public void buttonClick(ClickEvent event) {
						// Open Search
						MedicalPrescriptionView view = new MedicalPrescriptionView(
								session);
						MyVaadinUI.getNavigationManager().navigateTo(view);
					}
				});
		addMedicationButton.setEnabled(session.getSessionState().isEditable());
		mediNoteButtons.addComponent(addMedicationButton);

		updateButtons();
	}

	private void updateButtons() {
		Collection<SessionState> states = session.getSessionState()
				.getPossibleNextStateType();

		int componentCount = 0;

		boolean started = states.contains(SessionState.STARTED);
		if (started)
			componentCount++;
		startSessionButton.setVisible(started);

		boolean finished = states.contains(SessionState.FINISHED);
		if (finished)
			componentCount++;
		finishSessionButton.setVisible(finished);

		boolean aborted = states.contains(SessionState.ABORTED);
		if (aborted)
			componentCount++;
		abortSessionButton.setVisible(aborted);

		boolean reopened = states.contains(SessionState.REOPENED);
		if (reopened)
			componentCount++;
		reopenSessionButton.setVisible(reopened);

		boolean cancelled = states.contains(SessionState.CANCELLED);
		if (cancelled)
			componentCount++;
		cancelSessionButton.setVisible(cancelled);

		boolean archived = states.contains(SessionState.ARCHIVED);
		if (archived)
			componentCount++;
		archiveSessionButton.setVisible(archived);

		String width = (100 / componentCount) + "%";
		startSessionButton.setWidth(width);
		finishSessionButton.setWidth(width);
		abortSessionButton.setWidth(width);
		reopenSessionButton.setWidth(width);
		cancelSessionButton.setWidth(width);
		archiveSessionButton.setWidth(width);
	}

	private void buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");

		// back to home button

		mainLayout.addComponent(buildInfo());
		// Create title field
		tf = new TextArea("Session notes");
		tf.setWidth("100%");
		tf.setHeight("320px");
		tf.setTextChangeTimeout(300);
		tf.setTextChangeEventMode(AbstractTextField.TextChangeEventMode.TIMEOUT);
		tf.addTextChangeListener(new FieldEvents.TextChangeListener() {
			public void textChange(FieldEvents.TextChangeEvent event) {
				noteValue = event.getText();
				// patientSearch();
			}
		});

		// only enable the note field if the session is started
		if (!((session.getSessionState() == SessionState.STARTED) || (session
				.getSessionState() == SessionState.REOPENED))) {
			tf.setEnabled(false);
		}

		mainLayout.addComponent(tf);
		// add add Note button
		Button addNote = new Button("Add note", new Button.ClickListener() {
			@Override
			public void buttonClick(ClickEvent event) {
				Note note = ds.saveOrUpdate(new Note(tf.getValue()));
				session.addNote(note);
				session = ds.saveOrUpdate(session);
				tf.setValue("");
			}
		});
		mainLayout.addComponent(addNote);
	}
}