package ch.bfh.bti7081.s2013.pink.view;

import java.text.SimpleDateFormat;

import ch.bfh.bti7081.s2013.pink.MyVaadinUI;
import ch.bfh.bti7081.s2013.pink.SessionView;
import ch.bfh.bti7081.s2013.pink.model.HibernateDataSource;
import ch.bfh.bti7081.s2013.pink.model.Patient;
import ch.bfh.bti7081.s2013.pink.model.Session;
import ch.bfh.bti7081.s2013.pink.model.SessionState;

import com.vaadin.addon.touchkit.ui.NavigationButton;
import com.vaadin.addon.touchkit.ui.NavigationButton.NavigationButtonClickEvent;
import com.vaadin.addon.touchkit.ui.NavigationButton.NavigationButtonClickListener;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.ui.ComponentContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

/**
 * VIew class to display an overview of the next session/patient.
 * 
 * @author Marco Berger <lostchall@gmail.com>
 */
public class PatientOverview extends CustomComponent {
	private static final long serialVersionUID = -6396971132171425883L;

	private SimpleDateFormat dateFormat = new SimpleDateFormat();
	private HorizontalLayout mainLayout;

	private Label name;
	private Label sessionBegin;

	private Patient patient;
	private Session session;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public PatientOverview(Session session) {
		this.patient = session.getPatient();
		this.session = session;
		setCompositionRoot(buildMainLayout());
	}

	@SuppressWarnings("serial")
	private ComponentContainer buildMainLayout() {
		VerticalComponentGroup box = new VerticalComponentGroup();
		// common part: create layout
		mainLayout = new HorizontalLayout();
		box.addComponent(mainLayout);
		mainLayout.setWidth("100%");

		// VerticalLayout content = new VerticalLayout();

		VerticalLayout text = new VerticalLayout();
		// Layout buttons = new VerticalLayout();

		// Name
		name = new Label();
		name.setValue(patient.getFirstName() + " " + patient.getName());
		text.addComponent(name);

		// Adds the button to start the patient session
		NavigationButton showDetails = new NavigationButton(
				"Show Patient Details");
		showDetails.addClickListener(new NavigationButtonClickListener() {
			@Override
			public void buttonClick(NavigationButtonClickEvent event) {
				PatientDetailView detailedPatientView = new PatientDetailView(
						patient);
				MyVaadinUI.getNavigationManager().navigateTo(
						detailedPatientView);
			}
		});
		showDetails.setWidth("100%");
		box.addComponent(showDetails);

		// SessionBegin
		sessionBegin = new Label();
		String startTime = dateFormat.format(session.getTimeStart());
		sessionBegin.setValue("Session begin: " + startTime + " ("
				+ session.getSessionState() + ")");
		text.addComponent(sessionBegin);

		// Adds the button to start the patient session
		NavigationButton startSession = new NavigationButton("Show Session");
		startSession.addClickListener(new NavigationButtonClickListener() {

			@Override
			public void buttonClick(NavigationButtonClickEvent event) {
				session.changeState(SessionState.STARTED);
				HibernateDataSource.getInstance().saveOrUpdate(session);
				SessionView sessionView = new SessionView(session, patient);
				MyVaadinUI.getNavigationManager().navigateTo(sessionView);
			}
		});
		startSession.setWidth("100%");
		box.addComponent(startSession);

		// if (patient.getImageUrl() != null)
		// mainLayout.addComponent(new Image(null, new ClassResource(patient
		// .getImageUrl())));
		text.setExpandRatio(name, 1.0f);
		text.setExpandRatio(sessionBegin, 1.0f);
		mainLayout.addComponent(text);
		mainLayout.setExpandRatio(text, 2.0f);

		return box;
	}
}